// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"context"
	"sync"

	"github.com/google/go-github/v41/github"
)

type TeamsClient struct {
	GetTeamMembershipBySlugStub        func(context.Context, string, string, string) (*github.Membership, *github.Response, error)
	getTeamMembershipBySlugMutex       sync.RWMutex
	getTeamMembershipBySlugArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 string
		arg4 string
	}
	getTeamMembershipBySlugReturns struct {
		result1 *github.Membership
		result2 *github.Response
		result3 error
	}
	getTeamMembershipBySlugReturnsOnCall map[int]struct {
		result1 *github.Membership
		result2 *github.Response
		result3 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *TeamsClient) GetTeamMembershipBySlug(arg1 context.Context, arg2 string, arg3 string, arg4 string) (*github.Membership, *github.Response, error) {
	fake.getTeamMembershipBySlugMutex.Lock()
	ret, specificReturn := fake.getTeamMembershipBySlugReturnsOnCall[len(fake.getTeamMembershipBySlugArgsForCall)]
	fake.getTeamMembershipBySlugArgsForCall = append(fake.getTeamMembershipBySlugArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 string
		arg4 string
	}{arg1, arg2, arg3, arg4})
	stub := fake.GetTeamMembershipBySlugStub
	fakeReturns := fake.getTeamMembershipBySlugReturns
	fake.recordInvocation("GetTeamMembershipBySlug", []interface{}{arg1, arg2, arg3, arg4})
	fake.getTeamMembershipBySlugMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4)
	}
	if specificReturn {
		return ret.result1, ret.result2, ret.result3
	}
	return fakeReturns.result1, fakeReturns.result2, fakeReturns.result3
}

func (fake *TeamsClient) GetTeamMembershipBySlugCallCount() int {
	fake.getTeamMembershipBySlugMutex.RLock()
	defer fake.getTeamMembershipBySlugMutex.RUnlock()
	return len(fake.getTeamMembershipBySlugArgsForCall)
}

func (fake *TeamsClient) GetTeamMembershipBySlugCalls(stub func(context.Context, string, string, string) (*github.Membership, *github.Response, error)) {
	fake.getTeamMembershipBySlugMutex.Lock()
	defer fake.getTeamMembershipBySlugMutex.Unlock()
	fake.GetTeamMembershipBySlugStub = stub
}

func (fake *TeamsClient) GetTeamMembershipBySlugArgsForCall(i int) (context.Context, string, string, string) {
	fake.getTeamMembershipBySlugMutex.RLock()
	defer fake.getTeamMembershipBySlugMutex.RUnlock()
	argsForCall := fake.getTeamMembershipBySlugArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4
}

func (fake *TeamsClient) GetTeamMembershipBySlugReturns(result1 *github.Membership, result2 *github.Response, result3 error) {
	fake.getTeamMembershipBySlugMutex.Lock()
	defer fake.getTeamMembershipBySlugMutex.Unlock()
	fake.GetTeamMembershipBySlugStub = nil
	fake.getTeamMembershipBySlugReturns = struct {
		result1 *github.Membership
		result2 *github.Response
		result3 error
	}{result1, result2, result3}
}

func (fake *TeamsClient) GetTeamMembershipBySlugReturnsOnCall(i int, result1 *github.Membership, result2 *github.Response, result3 error) {
	fake.getTeamMembershipBySlugMutex.Lock()
	defer fake.getTeamMembershipBySlugMutex.Unlock()
	fake.GetTeamMembershipBySlugStub = nil
	if fake.getTeamMembershipBySlugReturnsOnCall == nil {
		fake.getTeamMembershipBySlugReturnsOnCall = make(map[int]struct {
			result1 *github.Membership
			result2 *github.Response
			result3 error
		})
	}
	fake.getTeamMembershipBySlugReturnsOnCall[i] = struct {
		result1 *github.Membership
		result2 *github.Response
		result3 error
	}{result1, result2, result3}
}

func (fake *TeamsClient) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.getTeamMembershipBySlugMutex.RLock()
	defer fake.getTeamMembershipBySlugMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *TeamsClient) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}
