#!/bin/bash

function filterExcludedAndGeneratedFiles {
    local excluded_files
    excluded_files=(
        '(^|/)\.git/'
        '(^|/)\go/pkg/mod/'
        '(^|/)go.mod$'
        '(^|/)go.sum$'
        '\.html$'
        '\.json$'
        '(^|/)LICENSE$'
        '\.md$'
    )

    local filter
    filter=$(local IFS='|' ; echo "${excluded_files[*]}")

    read -rd '' -a files <<<"$@"
    for f in "${files[@]}"; do
        file=$(echo "$f" | grep -Ev "$filter" | sort -u)
        if [ -n "$file" ]; then
            head -n8 "$file" | grep -qE '// Code generated by' || echo "$file"
        fi
    done
}