basePath: /api/v1
definitions:
  apis.JSONResult:
    properties:
      Code:
        type: integer
      Message:
        type: string
      Response: {}
    type: object
  github.RegistrationToken:
    properties:
      expires_at:
        $ref: '#/definitions/github.Timestamp'
      token:
        type: string
    type: object
  github.Timestamp:
    properties:
      time.Time:
        type: string
    type: object
info:
  contact:
    email: lindluni@github.com
    name: GitHub Professional Services
    url: https://github.com/lindluni/actions-runner-manager
  description: API for managing GitHub organization Runner Groups
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Action Runner Manager API
  version: 0.1.0
paths:
  /groups-create/{team}:
    get:
      description: Creates a new GitHub Action organization runner group named with
        the team slug
      parameters:
      - description: Canonical **slug** of the GitHub team
        in: path
        name: team
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: desc
          schema:
            allOf:
            - $ref: '#/definitions/apis.JSONResult'
            - properties:
                data:
                  type: string
              type: object
      security:
      - ApiKeyAuth: []
      summary: Create a new GitHub Action organization Runner Group
      tags:
      - groups
  /token-register/{team}:
    get:
      description: Creates a new GitHub Action organization runner removal token that
        can be used to configure GitHub Action runners at the organization level
      parameters:
      - description: Canonical **slug** of the GitHub team
        in: path
        name: team
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github.RegistrationToken'
      security:
      - ApiKeyAuth: []
      summary: Create a new GitHub Action organization runner registration token
      tags:
      - tokens
  /token-remove/{team}:
    get:
      description: Creates a new GitHub Action organization runner removal token that
        can be used remove a GitHub Action runners at the organization level
      parameters:
      - description: Canonical **slug** of the GitHub team
        in: path
        name: team
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github.RegistrationToken'
      security:
      - ApiKeyAuth: []
      summary: Create a new GitHub Action organization runner removal token
      tags:
      - tokens
securityDefinitions:
  APIKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
