basePath: /api/v1
definitions:
  apis.JSONResultSuccess:
    properties:
      Code:
        type: integer
      Response: {}
    type: object
  apis.listResponse:
    properties:
      repos:
        items:
          type: string
        type: array
      runners:
        items:
          type: string
        type: array
    type: object
  github.RegistrationToken:
    properties:
      expires_at:
        $ref: '#/definitions/github.Timestamp'
      token:
        type: string
    type: object
  github.Timestamp:
    properties:
      time.Time:
        type: string
    type: object
host: hostname
info:
  contact:
    email: lindluni@github.com
    name: GitHub Professional Services
    url: https://github.com/lindluni/actions-runner-manager
  description: API for managing GitHub organization Runner Groups
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Action Runner Manager API
  version: 0.1.0
paths:
  /groups-create:
    get:
      description: Creates a new GitHub Action organization runner group named with
        the team slug
      parameters:
      - description: Canonical **slug** of the GitHub team
        in: path
        name: team
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/apis.JSONResultSuccess'
            - properties:
                Code:
                  type: integer
                Response:
                  type: string
              type: object
      security:
      - ApiKeyAuth: []
      summary: Create a new GitHub Action organization Runner Group
      tags:
      - Groups
  /groups-delete:
    get:
      description: Deletes an existing GitHub Action organization runner group named
        with the team slug
      parameters:
      - description: Canonical **slug** of the GitHub team
        in: path
        name: team
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/apis.JSONResultSuccess'
            - properties:
                Code:
                  type: integer
                Response:
                  type: string
              type: object
      security:
      - ApiKeyAuth: []
      summary: Deletes an existing GitHub Action organization Runner Group
      tags:
      - Groups
  /groups-list:
    get:
      description: List all repositories and runners assigned to a GitHub Action organization
        runner group named with the team slug
      parameters:
      - description: Canonical **slug** of the GitHub team
        in: path
        name: team
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/apis.JSONResultSuccess'
            - properties:
                Code:
                  type: integer
                Response:
                  $ref: '#/definitions/apis.listResponse'
              type: object
      security:
      - ApiKeyAuth: []
      summary: List all resources associated with a GitHub Action organization Runner
        Group
      tags:
      - Groups
  /repos-add:
    get:
      description: Adds new repositories to an existing GitHub Actions organization
        named with the team slug
      parameters:
      - description: Canonical **slug** of the GitHub team
        in: path
        name: team
        required: true
        type: string
      - description: Comma-seperated list of repository slugs
        in: path
        items:
          type: string
        name: repos
        required: true
        type: array
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/apis.JSONResultSuccess'
            - properties:
                Code:
                  type: integer
                Response:
                  type: string
              type: object
      security:
      - ApiKeyAuth: []
      summary: Add new repositories to an existing GitHub Actions organization runner
        group
      tags:
      - Repos
  /repos-remove:
    get:
      description: Removes existing repositories to an existing GitHub Actions organization
        named with the team slug
      parameters:
      - description: Canonical **slug** of the GitHub team
        in: path
        name: team
        required: true
        type: string
      - description: Comma-seperated list of repository slugs
        in: path
        items:
          type: string
        name: repos
        required: true
        type: array
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/apis.JSONResultSuccess'
            - properties:
                Code:
                  type: integer
                Response:
                  type: string
              type: object
      security:
      - ApiKeyAuth: []
      summary: Remove existing repositories from an existing GitHub Actions organization
        runner group
      tags:
      - Repos
  /repos-set:
    get:
      description: Replaces all existing repositories in an existing GitHub Actions
        organization named with the team slug with a new set of repositories
      parameters:
      - description: Canonical **slug** of the GitHub team
        in: path
        name: team
        required: true
        type: string
      - description: Comma-seperated list of repository slugs
        in: path
        items:
          type: string
        name: repos
        required: true
        type: array
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/apis.JSONResultSuccess'
            - properties:
                Code:
                  type: integer
                Response:
                  type: string
              type: object
      security:
      - ApiKeyAuth: []
      summary: Replaces all existing repositories in an existing GitHub Actions organization
        runner group with a new set of repositories
      tags:
      - Repos
  /token-register:
    get:
      description: Creates a new GitHub Action organization runner removal token that
        can be used to configure GitHub Action runners at the organization level
      parameters:
      - description: Canonical **slug** of the GitHub team
        in: path
        name: team
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/apis.JSONResultSuccess'
            - properties:
                Code:
                  type: integer
                Response:
                  $ref: '#/definitions/github.RegistrationToken'
              type: object
      security:
      - ApiKeyAuth: []
      summary: Create a new GitHub Action organization runner registration token
      tags:
      - Tokens
  /token-remove:
    get:
      description: Creates a new GitHub Action organization runner removal token that
        can be used remove a GitHub Action runners at the organization level
      parameters:
      - description: Canonical **slug** of the GitHub team
        in: path
        name: team
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/apis.JSONResultSuccess'
            - properties:
                Code:
                  type: integer
                Response:
                  $ref: '#/definitions/github.RegistrationToken'
              type: object
      security:
      - ApiKeyAuth: []
      summary: Create a new GitHub Action organization runner removal token
      tags:
      - Tokens
securityDefinitions:
  APIKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
