#
# SPDX-License-Identifier: Apache-2.0
#
name: Continuous Integration
on:
  pull_request:
  workflow_dispatch:
env:
  GOBIN: ${{ github.workspace }}/bin
  PATH: ${{ github.workspace }}/bin:/bin:/usr/bin:/sbin:/usr/sbin:/usr/local/bin:/usr/local/sbin
  GOVER: 1.17.3
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ env.GOVER }}
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Lint Code
      run: make lint
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ env.GOVER }}
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Run Tests
      run: make tests