#
# SPDX-License-Identifier: Apache-2.0
#
name: Continuous Deployment
on:
  push:
    branches:
      - main
  workflow_dispatch:
permissions:
  contents: read
  packages: write
env:
  GOBIN: ${{ github.workspace }}/bin
  PATH: ${{ github.workspace }}/bin:/bin:/usr/bin:/sbin:/usr/sbin:/usr/local/bin:/usr/local/sbin
  GOVER: 1.17.3
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GOVER }}
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Lint Code
        run: make lint
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GOVER }}
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Run Tests
        run: make tests
        env:
          MANAGER_APP_ID: ${{ secrets.MANAGER_APP_ID }}
          MANAGER_APP_INSTALLATION_ID: ${{ secrets.MANAGER_APP_INSTALLATION_ID }}
          MANAGER_APP_PRIVATE_KEY: ${{ secrets.MANAGER_APP_PRIVATE_KEY }}
          MANAGER_ADMIN_PAT: ${{ secrets.MANAGER_ADMIN_PAT }}
          MANAGER_ORG: ${{ secrets.MANAGER_ORG }}
          MANAGER_USER: ${{ secrets.MANAGER_USER }}
  build-and-publish:
    name: Build and Publish
    runs-on: ubuntu-latest
    needs:
      - lint
      - test
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Set outputs
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - name: Check outputs
        run: echo ${{ steps.vars.outputs.sha_short }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:${{ steps.vars.outputs.sha_short }}
            ghcr.io/${{ github.repository }}:latest