#
# SPDX-License-Identifier: Apache-2.0
#
name: Publish Container
on:
  release:
    types:
      - created
permissions:
  contents: read
  packages: write
jobs:
  build-and-publish:
    name: Build and Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Parse Tag
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: >-
            ghcr.io/${{ github.repository }}:${{ steps.vars.outputs.tag }}
