#
# SPDX-License-Identifier: Apache-2.0
#
name: Publish Container
on:
  workflow_dispatch:
    inputs:
      tag:
        default: ""
        description: "Image tag to publish"
        required: true
        type: string
permissions:
  packages: write
jobs:
  build-and-publish:
    name: Build and Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/{{ github.repository }}:${{ inputs.tag }}
