#
# SPDX-License-Identifier: Apache-2.0
#
name: Create Release
on:
  push:
    tags:
      - '[0-9]+\.[0-9]+\.[0-9]+'
permissions:
  contents: write
jobs:
  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Create Binaries
        run: make release
      - name: Parse Tag
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/actions-runner-manager
          generate_release_notes: true
          name: ${{ steps.vars.outputs.tag }}
          tag_name: ${{ steps.vars.outputs.tag }}
